### ISSUE TITLE
MongoTopSample missing from Documentation

### ISSUE THREAD

**Issue by cpheps** [newrelic/nri-mongodb#29]
##### Description of the problem

The `MongodTopSample` is missing from documentation. 

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by ccheek21** [comment]
Request has been sent to documentation team

**Comment by ccheek21** [comment]
Docs updated
