### ISSUE TITLE
Default Dashboard Issue

### ISSUE THREAD

**Issue by thezackm** [newrelic/nri-mongodb#56]
## Description
The default dashboard for MongoDB in NROne has several widgets querying against `MongoSample`, which results in empty/blank charts.

## Steps to Reproduce
Navigate to `Infrastructure` >> `Third-party services` >> `MongoDB Dashboard` in NROne

**Comment by roobre** [comment]
current query: `SELECT latest(totalDatabases) AS Databases FROM MongoSample`
should be: `SELECT uniqueCount(entityName) AS 'Databases' FROM MongoDatabaseSample`

**Comment by gsanchezgavier** [comment]
Hi @thezackm the integration only reports `MongoSample` when a cluster is being monitored as the [docs](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration#metrics) state.

**Comment by thezackm** [comment]
ah, good call @gsanchezgavier! closing this one out. thanks!
