### ISSUE TITLE
MongoDB Atlas

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-mongodb#70]
Our Documentation says: MongoDB Atlas is supported for tiers M10 and above.

However, it has been reported that in general we do not have enough documentation for that.

We should test the whole solution again, verify any limitation and improve the documentation.

**Comment by paologallinaharbur** [comment]
Note that even if the library does not support that we could still perform a spike to check if we can add ourself the DNS seedlist support  at integration level

**Comment by mangulonr** [comment]
Ping me to get more info about creating a M10 test cluster

**Comment by mangulonr** [comment]
Atlas support has been released.
https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/

Closing the issue

**Comment by mangulonr** [comment]
Atlas support has been released.
https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/

Closing the issue
