### ISSUE TITLE
Add Flag to Disable MongoTopSample

### ISSUE THREAD

**Issue by dieskim** [newrelic/nri-mongodb#88]
## Is your feature request related to a problem? Please describe.
CPU and Memory Usage for nri-mongodb seems very high due to collectTop / MongoTopSample

## Feature Description
Add flag to disable collectTop / MongoTopSample

## Additional context
We have added the nri-mongodb integration on our Servers. CPU and Memory Usage for nri-mongodb seems very high and the amount of data being sent to New Relic is also high.

Is there currently a way to disable collectTop that generates MongodTopSample? Or something someone can add easily? Or is this something we should look into adding and submitting a pull request for? 

We are already excluding ingest of this data but dont want to keep collecting them on the server side as it seems to use alot of CPU and Mem resources.

We really only need Cluster Health related metrics, the rest we can debug manually on servers. Its nice to have on New Relic side but ingest amount seems extremely high and CPY and Mem usage also seem high.

## Priority
Really Want

**Comment by marcsanmi** [comment]
Hi @dieskim,

We are in a kind of "feature freeze" for this integration until we finish https://github.com/newrelic/nri-mongodb/issues/71 which we have recently started.

**Comment by dieskim** [comment]
@marcsanmi for now I found a temp solution for this - I have actually just removed the collectTop function and rebuilt the module for now, its a hacked together solution for now but would be better if we could disable this with a param. I am happy to put in some work on this if needed once the "feature freeze" is over - I would just need to make sure what the correct/expected method for this would be. Thanks

**Comment by alvarocabanas** [comment]
As soon as we release the new version we will let you know.

**Comment by dieskim** [comment]
hi, wondering if this feature request was added or what the final result was?

**Comment by paologallinaharbur** [comment]
Hi! The whole integration is about to get deprecated and the new one is more configurable. 

It follows a different approach (based on dimensional metrics and Prometheus), but there is a config to enable/disable top metrics
```
top_stats | Enable/Disable collection of Top Admin metrics
```

https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/

**Comment by dieskim** [comment]
ok thanks - I am asking because I saw my servers get a new update for nri-mongodb and was not sure - I guess I will wait for this new version. Thanks
