### ISSUE TITLE
Can we use this repo to config Mongo atlas integrate with New Relic

### ISSUE THREAD

**Issue by tharinduug** [newrelic/nri-mongodb#91]
I'm try to integrate MR and MongoDB atlas by using this repo. I have renamed  mongodb-atlas-config.yml and added required configurations. But getting below error when try to execute.

[ERR] Invalid arguments: Must supply a cluster name to identify this Mongodb cluster. Use MongodbClusterName config parameter

Could you please share guidance to configure 

Thanks
Tharindu

**Comment by kang-makes** [comment]
Hi @tharinduug,

It seems that the integration is misconfigured, have you followed the documentation [here](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration/#instance-settings)?

There are variables missing in the YAML for the integration.

**Comment by tharinduug** [comment]
HI @kang-makes 
I just filled only existing variables only. Not added new. I will go through your shared doc and retry.
If you have sample config file ( related Mongo Atlas ). 

Thanks
Tharindu

**Comment by kang-makes** [comment]
Hi!

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs.

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
